### ISSUE TITLE
After update from 7.6.1 to 8.3.4 fail in production

### ISSUE THREAD

**Issue by Avi-ADAM** [mhkeller/layercake#233] opened 2024-09-03 14:43 UTC
I am using it With sveltekit and enjoing this great feature for a while.
When updating from from 7.6.1 to 8.3.4 It was all good in development server but on production With vercel I got the following error and 500 for some of my website pages.
```


import { InternSet, ascending } from "d3-array";
         ^^^^^^^^^
SyntaxError: Named export 'InternSet' not found. The requested module 'd3-array' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'd3-array';
const { InternSet, ascending } = pkg;


```
After undergrating the error stoped.

**Comment by mhkeller** [comment] 2024-09-19 00:35
Hm, Can you create a bare minimum reproduction repo so I can test this issue? Please follow the instructions here for creating a reproduction: https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff

**Comment by mhkeller** [comment] 2024-10-19 22:23
I'm closing this because I don't think this relates to LayerCake but please reopen if you can pinpoint the problem further.

**Closed by mhkeller** 2024-10-19 22:23 UTC
Labels: need-more-information
